/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Bond
 */
public class CompraParcelas extends javax.swing.JFrame {
    DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form CompraParcelas
     */
    public CompraParcelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        uma = new javax.swing.JRadioButton();
        cinco = new javax.swing.JRadioButton();
        duas = new javax.swing.JRadioButton();
        tres = new javax.swing.JRadioButton();
        quatro = new javax.swing.JRadioButton();
        calcular = new javax.swing.JButton();
        limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data da Compra:");

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Valor: R$");

        grupo1.add(uma);
        uma.setText("1x");

        grupo1.add(cinco);
        cinco.setText("5x");

        grupo1.add(duas);
        duas.setText("2x");

        grupo1.add(tres);
        tres.setText("3x");

        grupo1.add(quatro);
        quatro.setText("4x");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(uma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(duas)
                        .addGap(30, 30, 30)
                        .addComponent(tres)
                        .addGap(37, 37, 37)
                        .addComponent(quatro)
                        .addGap(44, 44, 44)
                        .addComponent(cinco)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(valor))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uma)
                    .addComponent(duas)
                    .addComponent(tres)
                    .addComponent(quatro)
                    .addComponent(cinco))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(limpar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
       LocalDate dataF = LocalDate.parse(data.getText(),formatar);
       float parcela = Float.parseFloat(valor.getText());
       
        if(uma.isSelected()){
           JOptionPane.showMessageDialog(null, "O pagamento vai ser no valor de R$ "+valor.getText()+""
                   + "\n Data do Pagamento: "+dataF.format(formatar), "Pagamento Único", JOptionPane.INFORMATION_MESSAGE);
       }else if(duas.isSelected()){
           parcela = parcela/2;
           JOptionPane.showMessageDialog(null, "O pagamento vai ser no valor de R$ "+parcela+" por parcela"
                   + "\n Data do Primeiro Pagamento: "+dataF.plusDays(30).format(formatar)
                   + "\n Data do Segundo Pagamento: "+dataF.plusDays(60).format(formatar), "Pagemento Parcelado", JOptionPane.INFORMATION_MESSAGE);
       }else if(tres.isSelected()){
           parcela = parcela/3;
           JOptionPane.showMessageDialog(null, "O pagamento vai ser no valor de R$ "+parcela+" por parcela"
                   + "\n Data do Primeiro Pagamento: "+dataF.plusDays(30).format(formatar)
                   + "\n Data do Segundo Pagamento: "+dataF.plusDays(60).format(formatar)
                   + "\n Data do Terceiro Pagamento: "+dataF.plusDays(90).format(formatar),"Pagemento Parcelado", JOptionPane.INFORMATION_MESSAGE);
       }else if(quatro.isSelected()){
           parcela = parcela/4;
           JOptionPane.showMessageDialog(null, "O pagamento vai ser no valor de R$ "+parcela+" por parcela"
                   + "\n Data do Primeiro Pagamento: "+dataF.plusDays(30).format(formatar)
                   + "\n Data do Segundo Pagamento: "+dataF.plusDays(60).format(formatar)
                   + "\n Data do Terceiro Pagamento: "+dataF.plusDays(90).format(formatar)
                   + "\n Data do Quarto Pagamento: "+dataF.plusDays(120).format(formatar),"Pagemento Parcelado", JOptionPane.INFORMATION_MESSAGE);
       }else if(cinco.isSelected()){
           parcela = parcela/5;
           JOptionPane.showMessageDialog(null, "O pagamento vai ser no valor de R$ "+parcela+" por parcela"
                   + "\n Data do Primeiro Pagamento: "+dataF.plusDays(30).format(formatar)
                   + "\n Data do Segundo Pagamento: "+dataF.plusDays(60).format(formatar)
                   + "\n Data do Terceiro Pagamento: "+dataF.plusDays(90).format(formatar)
                   + "\n Data do Quarto Pagamento: "+dataF.plusDays(120).format(formatar)
                   + "\n Data do Quinto Pagamento: "+dataF.plusDays(150).format(formatar),"Pagemento Parcelado", JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(null, "Seleção Inválida!","Erro", JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_calcularActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        data.setText(null);
        valor.setText(null);
        grupo1.setSelected(null, rootPaneCheckingEnabled);
    }//GEN-LAST:event_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraParcelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraParcelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JRadioButton cinco;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JRadioButton duas;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JRadioButton quatro;
    private javax.swing.JRadioButton tres;
    private javax.swing.JRadioButton uma;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
